kind: Service
apiVersion: v1
metadata:
  name: spring-docker
spec:
  selector:
    app: spring-docker
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker
spec:
  selector:
      matchLabels:
        app: spring-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-docker
    spec:
      containers:
        - name: spring-docker
          image: sanuj5/heisenberg:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
